# Generated by Django 5.0.12 on 2025-03-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lp', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('token0', models.JSONField(blank=True, null=True)),
                ('token1', models.JSONField(blank=True, null=True)),
                ('reserve0', models.CharField(blank=True, max_length=50, null=True)),
                ('reserve1', models.CharField(blank=True, max_length=50, null=True)),
                ('fees0', models.CharField(blank=True, max_length=50, null=True)),
                ('fees1', models.CharField(blank=True, max_length=50, null=True)),
                ('volume0', models.CharField(blank=True, max_length=50, null=True)),
                ('volume1', models.CharField(blank=True, max_length=50, null=True)),
                ('rate0', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('rate1', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('emissions', models.CharField(blank=True, max_length=50, null=True)),
                ('emissions_token', models.JSONField(blank=True, null=True)),
                ('staked0', models.CharField(blank=True, max_length=50, null=True)),
                ('staked1', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
