# Generated by Django 5.0.12 on 2025-03-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trace_id', models.CharField(blank=True, max_length=50, null=True)),
                ('in_tokens', models.JSONField(blank=True, null=True)),
                ('out_tokens', models.JSONField(blank=True, null=True)),
                ('in_amounts', models.JSONField(blank=True, null=True)),
                ('out_amounts', models.JSONField(blank=True, null=True)),
                ('gas_estimate', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('data_gas_estimate', models.IntegerField(blank=True, null=True)),
                ('gwei_per_gas', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('gas_estimate_value', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('in_values', models.JSONField(blank=True, null=True)),
                ('out_values', models.JSONField(blank=True, null=True)),
                ('net_out_value', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('price_impact', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('percent_diff', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('partner_fee_percent', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('path_id', models.CharField(blank=True, max_length=50, null=True)),
                ('path_viz', models.CharField(blank=True, max_length=50, null=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
