# Generated by Django 5.0.12 on 2025-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_swaptransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneLineUAQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USUI', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('uSOL', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('uADA', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('uPEPE', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('uSEI', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('uDOGE', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('uSHIB', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('uLINK', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('uAPT', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('uNEAR', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('uXRP', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UAQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('slippage_bips', models.PositiveIntegerField(blank=True, null=True)),
                ('token_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('pair_token', models.CharField(blank=True, max_length=20, null=True)),
                ('blockchain', models.CharField(blank=True, max_length=20, null=True)),
                ('user_address', models.CharField(blank=True, max_length=50, null=True)),
                ('pair_token_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('merchant_address', models.CharField(blank=True, max_length=50, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=50, null=True)),
                ('gas_fee_nominal', models.CharField(blank=True, max_length=50, null=True)),
                ('gas_fee_dollars', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('relayer_nonce', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=20, null=True)),
                ('exchange_rate_usd', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
