# Generated by Django 5.0.12 on 2025-03-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KyberswapRouteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_in', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_in', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_in_usd', models.CharField(blank=True, max_length=50, null=True)),
                ('token_in_market_price_available', models.BooleanField(default=False)),
                ('token_out', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_out', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_out_usd', models.CharField(blank=True, max_length=50, null=True)),
                ('token_out_market_price_available', models.BooleanField(default=False)),
                ('gas', models.CharField(blank=True, max_length=50, null=True)),
                ('gas_price', models.CharField(blank=True, max_length=50, null=True)),
                ('gas_usd', models.CharField(blank=True, max_length=50, null=True)),
                ('l1_fee_usd', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_fee', models.JSONField(blank=True, null=True)),
                ('route', models.JSONField(blank=True, null=True)),
                ('route_id', models.CharField(blank=True, max_length=50, null=True)),
                ('checksum', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
